version: '3'

services:

  gestao-produto:
    build:
      context: gestao-produto
      dockerfile: Dockerfile
    image: nodejs
    container_name: gestao-produto
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - .:/home/node
      - /home/node/node_modules
    command: npm start

  gestao-vendas:
    build:
      context: gestao-vendas
      dockerfile: Dockerfile
    image: nodejs
    container_name: gestao-vendas
    restart: unless-stopped
    ports:
      - "3002:3002"
    volumes:
      - .:/home/node
      - /home/node/node_modules
    command: npm start

  api-gateway:
    build:
      context: api-gateway
      dockerfile: Dockerfile
    image: nodejs
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node
      - /home/node/node_modules
    command: npm start
